// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { IGatsbyImageData } from "gatsby-plugin-image";

export interface IProjectFields {
    /** title */
    title: string;

    /** thumbnail */
    thumbnail: {
        gatsbyImageData: any;
        file: {
            url: string;
        };
    };

    /** description */
    description: {
        description: string;
    };

    /** content */
    content: {
        stacks: string[];
        tags: string[];
        app_link: string;
        github_link: string;
    };

    /** date */
    date?: string | undefined;

    /** resume */
    resume?: string | undefined;

    /** used */
    used: {
        used: string;
    } | null;

    /** about images */
    aboutImages?: Asset[] | undefined;

    /** lesson */
    lesson?: {
        lesson: string;
    } | null;

    /** conclusion */
    conclusion?: {
        conclusion: string;
    } | null;
}

/** Homepage project section */

export interface IProject extends Entry<IProjectFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "project";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export type CONTENT_TYPE = "project";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";

export interface ContentfulProject {
    id: string;
    title: string;
    thumbnail: {
        gatsbyImageData: IGatsbyImageData;
        file: {
            url: string;
        };
    };
    content: {
        stacks: string[];
        tags: string[];
        app_link: string;
        github_link: string;
    };
    description: {
        description: string;
    };
}
export interface ContentfulProjectObject {
    allContentfulProjects: {
        nodes: ContentfulProject[];
    };
}
